import type { ChartPreset, ChartPresetDefinition, ChartWidgetConfig } from './types'
import defaultMapGeoJsonTemplate from './json/370200.geojson?raw'

export const DEFAULT_CHART_COLORS = [
  '#1677ff',
  '#36cfc9',
  '#f59e0b',
  '#ef4444',
  '#8b5cf6',
  '#22c55e',
]

export const DEFAULT_MAP_GEOJSON_TEMPLATE = defaultMapGeoJsonTemplate

const PRESET_MAP: Record<ChartPreset, ChartPresetDefinition> = {
  'basic-line': {
    key: 'basic-line',
    title: '基础折线图',
    description: '单系列趋势展示',
    drawerCategory: '趋势',
    defaults: {
      chartPreset: 'basic-line',
      categoryField: 'name',
      valueField: 'value',
      smooth: true,
      showLegend: false,
      showTooltip: true,
      showLabel: false,
      showArea: false,
      areaOpacity: 20,
      lineWidth: 3,
      symbolSize: 10,
      colors: DEFAULT_CHART_COLORS,
    },
    staticDataExample: [
      { name: '周一', value: 120 },
      { name: '周二', value: 168 },
      { name: '周三', value: 142 },
      { name: '周四', value: 186 },
      { name: '周五', value: 210 },
    ],
  },
  'basic-bar': {
    key: 'basic-bar',
    title: '基础柱状图',
    description: '单系列柱状对比',
    drawerCategory: '柱状',
    defaults: {
      chartPreset: 'basic-bar',
      categoryField: 'name',
      valueField: 'value',
      showLegend: false,
      showTooltip: true,
      showLabel: true,
      barWidth: '45%',
      borderRadius: 6,
      colors: DEFAULT_CHART_COLORS,
    },
    staticDataExample: [
      { name: '一月', value: 320 },
      { name: '二月', value: 280 },
      { name: '三月', value: 356 },
      { name: '四月', value: 410 },
    ],
  },
  'stacked-bar': {
    key: 'stacked-bar',
    title: '堆叠柱状图',
    description: '多系列堆叠对比',
    drawerCategory: '柱状',
    defaults: {
      chartPreset: 'stacked-bar',
      categoryField: 'category',
      seriesField: 'series',
      valueField: 'value',
      showLegend: true,
      showTooltip: true,
      showLabel: false,
      barWidth: '50%',
      borderRadius: 4,
      colors: DEFAULT_CHART_COLORS,
    },
    staticDataExample: [
      { category: '华东', series: '已完成', value: 320 },
      { category: '华东', series: '处理中', value: 180 },
      { category: '华南', series: '已完成', value: 280 },
      { category: '华南', series: '处理中', value: 160 },
      { category: '华北', series: '已完成', value: 350 },
      { category: '华北', series: '处理中', value: 140 },
    ],
  },
  'percent-bar': {
    key: 'percent-bar',
    title: '百分比柱状图',
    description: '展示构成占比',
    drawerCategory: '柱状',
    defaults: {
      chartPreset: 'percent-bar',
      categoryField: 'category',
      seriesField: 'series',
      valueField: 'value',
      showLegend: true,
      showTooltip: true,
      showLabel: true,
      barWidth: '56%',
      borderRadius: 4,
      colors: DEFAULT_CHART_COLORS,
    },
    staticDataExample: [
      { category: '安全', series: '完成', value: 80 },
      { category: '安全', series: '未完成', value: 20 },
      { category: '巡检', series: '完成', value: 72 },
      { category: '巡检', series: '未完成', value: 28 },
      { category: '处置', series: '完成', value: 66 },
      { category: '处置', series: '未完成', value: 34 },
    ],
  },
  'grouped-bar': {
    key: 'grouped-bar',
    title: '分组柱状图',
    description: '多系列并列对比',
    drawerCategory: '柱状',
    defaults: {
      chartPreset: 'grouped-bar',
      categoryField: 'category',
      seriesField: 'series',
      valueField: 'value',
      showLegend: true,
      showTooltip: true,
      showLabel: false,
      barWidth: '36%',
      borderRadius: 6,
      colors: DEFAULT_CHART_COLORS,
    },
    staticDataExample: [
      { category: '一季度', series: '今年', value: 320 },
      { category: '一季度', series: '去年', value: 280 },
      { category: '二季度', series: '今年', value: 356 },
      { category: '二季度', series: '去年', value: 310 },
      { category: '三季度', series: '今年', value: 410 },
      { category: '三季度', series: '去年', value: 365 },
    ],
  },
  'basic-horizontal-bar': {
    key: 'basic-horizontal-bar',
    title: '基础条形图',
    description: '横向排名对比',
    drawerCategory: '柱状',
    defaults: {
      chartPreset: 'basic-horizontal-bar',
      categoryField: 'name',
      valueField: 'value',
      showLegend: false,
      showTooltip: true,
      showLabel: true,
      barWidth: '52%',
      borderRadius: 6,
      colors: DEFAULT_CHART_COLORS,
    },
    staticDataExample: [
      { name: '事项 A', value: 420 },
      { name: '事项 B', value: 360 },
      { name: '事项 C', value: 300 },
      { name: '事项 D', value: 240 },
    ],
  },
  'stacked-horizontal-bar': {
    key: 'stacked-horizontal-bar',
    title: '堆叠条形图',
    description: '横向堆叠构成',
    drawerCategory: '柱状',
    defaults: {
      chartPreset: 'stacked-horizontal-bar',
      categoryField: 'category',
      seriesField: 'series',
      valueField: 'value',
      showLegend: true,
      showTooltip: true,
      showLabel: false,
      barWidth: '58%',
      borderRadius: 4,
      colors: DEFAULT_CHART_COLORS,
    },
    staticDataExample: [
      { category: '港区 A', series: '正常', value: 300 },
      { category: '港区 A', series: '异常', value: 55 },
      { category: '港区 B', series: '正常', value: 280 },
      { category: '港区 B', series: '异常', value: 72 },
      { category: '港区 C', series: '正常', value: 260 },
      { category: '港区 C', series: '异常', value: 48 },
    ],
  },
  'progress-bar': {
    key: 'progress-bar',
    title: '进度条',
    description: '任务完成率展示',
    drawerCategory: '柱状',
    defaults: {
      chartPreset: 'progress-bar',
      categoryField: 'name',
      valueField: 'value',
      valueField2: 'target',
      showLegend: false,
      showTooltip: true,
      showLabel: true,
      barWidth: '40%',
      borderRadius: 0,
      colors: DEFAULT_CHART_COLORS,
    },
    staticDataExample: [
      { name: '巡检任务', value: 78, target: 100 },
      { name: '隐患整改', value: 63, target: 100 },
      { name: '船舶靠泊', value: 92, target: 100 },
    ],
  },
  gauge: {
    key: 'gauge',
    title: '仪表盘',
    description: '单指标阈值展示',
    drawerCategory: '仪表',
    defaults: {
      chartPreset: 'gauge',
      nameField: 'name',
      valueField: 'value',
      valueField2: 'max',
      valueField3: 'min',
      showLegend: false,
      showTooltip: true,
      showLabel: true,
      showAxisLabel: true,
      showSplitLine: true,
      gaugeMin: 0,
      gaugeMax: 100,
      gaugeStartAngle: 210,
      gaugeEndAngle: -30,
      gaugeSplitNumber: 10,
      gaugeAxisLineWidth: 12,
      gaugeProgressWidth: 12,
      gaugePointerWidth: 6,
      gaugePointerLength: 68,
      gaugeShowPointer: true,
      gaugeShowProgress: true,
      gaugeDetailSuffix: '%',
      gaugeDetailFontSize: 24,
      colors: DEFAULT_CHART_COLORS,
    },
    staticDataExample: {
      name: '完成率',
      value: 76,
      min: 0,
      max: 100,
    },
  },
  pie: {
    key: 'pie',
    title: '饼图',
    description: '占比构成分析',
    drawerCategory: '分布',
    defaults: {
      chartPreset: 'pie',
      nameField: 'name',
      valueField: 'value',
      showLegend: true,
      showTooltip: true,
      showLabel: true,
      colors: DEFAULT_CHART_COLORS,
    },
    staticDataExample: [
      { name: '正常', value: 68 },
      { name: '预警', value: 18 },
      { name: '异常', value: 14 },
    ],
  },
  donut: {
    key: 'donut',
    title: '环形图',
    description: '中空环形占比图',
    drawerCategory: '分布',
    defaults: {
      chartPreset: 'donut',
      nameField: 'name',
      valueField: 'value',
      showLegend: true,
      showTooltip: true,
      showLabel: true,
      donutInnerRadius: 52,
      donutOuterRadius: 76,
      colors: DEFAULT_CHART_COLORS,
    },
    staticDataExample: [
      { name: '完成', value: 54 },
      { name: '处理中', value: 26 },
      { name: '未开始', value: 20 },
    ],
  },
  radar: {
    key: 'radar',
    title: '雷达图',
    description: '多维指标能力分析',
    drawerCategory: '分布',
    defaults: {
      chartPreset: 'radar',
      indicatorsField: 'indicators',
      radarSeriesField: 'series',
      valueField: 'value',
      showLegend: true,
      showTooltip: true,
      showLabel: false,
      showArea: true,
      areaOpacity: 18,
      colors: DEFAULT_CHART_COLORS,
    },
    staticDataExample: {
      indicators: [
        { name: '响应速度', max: 100 },
        { name: '处置效率', max: 100 },
        { name: '协同能力', max: 100 },
        { name: '安全质量', max: 100 },
        { name: '资源保障', max: 100 },
      ],
      series: [
        { name: '本月', value: [82, 76, 88, 90, 74] },
        { name: '上月', value: [74, 68, 80, 86, 70] },
      ],
    },
  },
  'area-map': {
    key: 'area-map',
    title: '区域地图',
    description: 'GeoJSON 区域着色图',
    drawerCategory: '地图',
    defaultLayout: { w: 10, h: 10, minW: 5, minH: 5 },
    defaults: {
      chartPreset: 'area-map',
      nameField: 'name',
      valueField: 'value',
      showLegend: false,
      showTooltip: true,
      showLabel: true,
      geoJsonSource: 'inline',
      geoJsonText: DEFAULT_MAP_GEOJSON_TEMPLATE,
      geoJsonNameProperty: 'name',
      mapRoam: true,
      mapZoom: 1,
      mapBorderColor: '#d0d7e2',
      mapEmphasisAreaColor: '#dce8ff',
      showVisualMap: true,
      visualMapStartColor: '#dce8ff',
      visualMapEndColor: '#1677ff',
      colors: DEFAULT_CHART_COLORS,
    },
    staticDataExample: [
      { name: '黄岛区', value: 120 },
      { name: '市南区', value: 90 },
      { name: '市北区', value: 56 },
    ],
  },
  'flow-map': {
    key: 'flow-map',
    title: '流向地图',
    description: 'GeoJSON 上展示流向关系',
    drawerCategory: '地图',
    defaultLayout: { w: 10, h: 10, minW: 5, minH: 5 },
    defaults: {
      chartPreset: 'flow-map',
      nodesField: 'nodes',
      linksField: 'links',
      nameField: 'name',
      lngField: 'lng',
      latField: 'lat',
      valueField: 'value',
      sourceField: 'source',
      targetField: 'target',
      showLegend: false,
      showTooltip: true,
      showLabel: true,
      geoJsonSource: 'inline',
      geoJsonText: DEFAULT_MAP_GEOJSON_TEMPLATE,
      geoJsonNameProperty: 'name',
      mapRoam: true,
      mapZoom: 1,
      mapAreaColor: '#f5f7fb',
      mapBorderColor: '#d0d7e2',
      mapEmphasisAreaColor: '#dce8ff',
      flowLineColor: '#1677ff',
      flowNodeColor: '#1677ff',
      lineWidth: 2,
      lineCurveness: 0.18,
      symbolSize: 12,
      flowNodeSize: 18,
      colors: DEFAULT_CHART_COLORS,
    },
    staticDataExample: {
      nodes: [
        { name: '市南区', lng: 120.3512, lat: 36.0666, value: 92 },
        { name: '市北区', lng: 120.3646, lat: 36.1140, value: 108 },
        { name: '李沧区', lng: 120.4244, lat: 36.1861, value: 86 },
        { name: '崂山区', lng: 120.6782, lat: 36.1149, value: 78 },
        { name: '城阳区', lng: 120.3385, lat: 36.2861, value: 96 },
        { name: '即墨区', lng: 120.5960, lat: 36.4272, value: 88 },
        { name: '胶州市', lng: 119.9187, lat: 36.2545, value: 72 },
        { name: '黄岛区', lng: 119.9188, lat: 35.8606, value: 114 },
      ],
      links: [
        { source: '市南区', target: '市北区', value: 36 },
        { source: '市南区', target: '崂山区', value: 28 },
        { source: '市北区', target: '李沧区', value: 32 },
        { source: '市北区', target: '城阳区', value: 26 },
        { source: '李沧区', target: '即墨区', value: 24 },
        { source: '胶州市', target: '城阳区', value: 22 },
        { source: '黄岛区', target: '市南区', value: 34 },
        { source: '黄岛区', target: '胶州市', value: 18 },
      ],
    },
  },
  funnel: {
    key: 'funnel',
    title: '漏斗图',
    description: '阶段转化分析',
    drawerCategory: '关系',
    defaults: {
      chartPreset: 'funnel',
      nameField: 'name',
      valueField: 'value',
      showLegend: false,
      showTooltip: true,
      showLabel: true,
      funnelSort: 'descending',
      colors: DEFAULT_CHART_COLORS,
    },
    staticDataExample: [
      { name: '受理', value: 1000 },
      { name: '审核', value: 760 },
      { name: '派发', value: 520 },
      { name: '完成', value: 380 },
    ],
  },
  scatter: {
    key: 'scatter',
    title: '散点图',
    description: '双维度分布关系',
    drawerCategory: '关系',
    defaults: {
      chartPreset: 'scatter',
      xField: 'x',
      yField: 'y',
      nameField: 'name',
      symbolSizeField: 'size',
      showLegend: false,
      showTooltip: true,
      showLabel: false,
      colors: DEFAULT_CHART_COLORS,
    },
    staticDataExample: [
      { name: '样本 A', x: 12, y: 68, size: 18 },
      { name: '样本 B', x: 18, y: 58, size: 14 },
      { name: '样本 C', x: 28, y: 84, size: 22 },
      { name: '样本 D', x: 34, y: 46, size: 12 },
    ],
  },
  'dual-axis': {
    key: 'dual-axis',
    title: '柱线组合图',
    description: '柱状与折线双轴',
    drawerCategory: '双轴',
    defaults: {
      chartPreset: 'dual-axis',
      categoryField: 'name',
      valueField: 'barValue',
      valueField2: 'lineValue',
      showLegend: true,
      showTooltip: true,
      showLabel: false,
      smooth: true,
      lineWidth: 3,
      barWidth: '42%',
      borderRadius: 6,
      colors: DEFAULT_CHART_COLORS,
    },
    staticDataExample: [
      { name: '一月', barValue: 320, lineValue: 72 },
      { name: '二月', barValue: 360, lineValue: 78 },
      { name: '三月', barValue: 400, lineValue: 84 },
      { name: '四月', barValue: 380, lineValue: 76 },
    ],
  },
  'grouped-dual-axis': {
    key: 'grouped-dual-axis',
    title: '分组柱线组合图',
    description: '分组柱与折线双轴',
    drawerCategory: '双轴',
    defaults: {
      chartPreset: 'grouped-dual-axis',
      categoryField: 'category',
      seriesField: 'series',
      valueField: 'barValue',
      valueField2: 'lineValue',
      showLegend: true,
      showTooltip: true,
      showLabel: false,
      smooth: true,
      lineWidth: 3,
      barWidth: '32%',
      borderRadius: 6,
      colors: DEFAULT_CHART_COLORS,
    },
    staticDataExample: [
      { category: '一月', series: 'A 组', barValue: 160, lineValue: 72 },
      { category: '一月', series: 'B 组', barValue: 120, lineValue: 65 },
      { category: '二月', series: 'A 组', barValue: 182, lineValue: 78 },
      { category: '二月', series: 'B 组', barValue: 136, lineValue: 70 },
      { category: '三月', series: 'A 组', barValue: 196, lineValue: 84 },
      { category: '三月', series: 'B 组', barValue: 150, lineValue: 74 },
    ],
  },
}

export const CHART_PRESET_LIST = Object.values(PRESET_MAP)

export const CHART_PRESET_GROUPS = CHART_PRESET_LIST.reduce<Record<string, ChartPresetDefinition[]>>(
  (result, item) => {
    if (!result[item.drawerCategory]) {
      result[item.drawerCategory] = []
    }
    result[item.drawerCategory].push(item)
    return result
  },
  {},
)

export const DEFAULT_CHART_PRESET: ChartPreset = 'basic-line'

export const getChartPresetDefinition = (preset?: string | null) =>
  PRESET_MAP[(preset as ChartPreset) || DEFAULT_CHART_PRESET] || PRESET_MAP[DEFAULT_CHART_PRESET]

export const resolveChartLegacyPreset = (config?: Partial<ChartWidgetConfig>): ChartPreset => {
  if (config?.chartPreset && PRESET_MAP[config.chartPreset]) {
    return config.chartPreset
  }

  switch (config?.chartType) {
    case 'bar':
      return 'basic-bar'
    case 'pie':
      return 'pie'
    case 'scatter':
      return 'scatter'
    case 'area':
      return 'basic-line'
    case 'line':
    default:
      return DEFAULT_CHART_PRESET
  }
}

export const createChartPresetConfig = (preset?: ChartPreset): Partial<ChartWidgetConfig> => {
  const definition = getChartPresetDefinition(preset)
  return {
    chartPreset: definition.key,
    dataSource: 'static',
    staticData: definition.staticDataExample,
    chartTitle: '',
    chartSubTitle: '',
    gridTop: 60,
    gridBottom: 60,
    gridLeft: '10%',
    gridRight: '10%',
    showAxisLabel: true,
    showSplitLine: true,
    geoJsonUrl: '',
    visualMapMin: undefined,
    visualMapMax: undefined,
    ...definition.defaults,
  }
}
