server {
    listen       80;
    server_name  localhost;

    location / {
        root   /code/portal-web;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /static/ {
        root   /code/portal-web;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
